openapi: 3.0.1
info:
  title: architecture 1 implementation swagger docs
servers:
  - url: https://localhost:3000
paths:
components:
  schemas:
  securitySchemes:
  responses:
  headers:
  examples:
  links:
